# TODO
name: Snapshot
on:
  workflow_dispatch:

env:
  TARGET_URL: https://tranquility2.github.io/

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: browser-actions/setup-chrome@latest
      - run: chrome --headless --disable-gpu --screenshot $TARGET_URL
      - run: ls -h
