# Used to screenshot a website 
name: Snapshot
on:
  workflow_dispatch:

env:
  TARGET_URL: https://tranquility2.github.io/
  OUTPUT_FILE: screenshot.png

jobs:
  take-snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Take the Screenshot
        uses: browser-actions/setup-chrome@latest
        # Running with --screenshot will produce a file named screenshot.png in the current working directory
        run: |
          chrome --headless --disable-gpu --screenshot $TARGET_URL
          ls -alh
      - name: Checkout repo
        uses: actions/checkout@v2
